import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import Provide from "@/components/layout/Provide";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex justify-center p-24 ">
        <Provide>
          {" "}
          <Navbar />
          <div className="absolute -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"> {children}</div>
        </Provide>
      </body>
    </html>
  );
}
